name: Build Godot Game

on:
  push:
    branches: [main]
  release:
    types: [published]

env:
  GODOT_VERSION: 4.4.1

jobs:
  export:
    name: Export All Platforms
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.4.1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Web
        run: |
          mkdir -p builds/web
          godot --headless --verbose --export-release "Web" builds/web/index.html

      - name: Export Windows
        run: |
          mkdir -p builds/win
          godot --headless --export-release "Windows Desktop" builds/win/Plouf-v01.exe

      - name: Export Linux
        run: |
          mkdir -p builds/linux
          godot --headless --export-release "Linux" builds/linux/plouf_v0.1.x86_64
          

      # Android
      #- name: Configure Java SDK path for Android export
      #  run: |
      #    echo 'export/android/android_sdk_path = "/usr/lib/jvm/java-17-openjdk-amd64/"' >> ~/.config/godot/editor_settings-4.4.tres

      #- name: Export Android
      #  run: |
      #    mkdir -p builds/android
      #    godot --headless --export-release "Android" builds/android/Plouf-v01.apk
      
      - name: List build files
        run: ls -R builds/

      - name: Upload all builds as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-builds
          path: builds/

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: builds/**/*.*
